apiVersion: v1
kind: Service
metadata:
  name: timeapp-service
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:435746439001:certificate/82229338-209b-43d2-b5b9-7902e662a182
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
    - port: 80
      targetPort: timeapp-port
      protocol: TCP
  selector:
    app: timeapp
  type: LoadBalancer
